import Link from "next/link";
import { Activity, ArrowRight, Check, Layers, Ruler, Shield } from "@/components/design-system/icons";
import { Button, SectionHeading, StatusTag, TechnicalPanel } from "@/components/design-system/primitives";

const systems = [
  { code: "01", title: "Parts", body: "Drawing-led routes for the interfaces that make hardware work.", href: "/parts/robot-joint-housing", tag: "TECHNICAL OBJECTS" },
  { code: "02", title: "Capabilities", body: "Process guidance grounded in geometry, workholding, and inspection.", href: "/capabilities/5-axis-machining", tag: "PROCESS FIT" },
  { code: "03", title: "Applications", body: "System views that connect part families to the product being built.", href: "/applications/humanoid-robots", tag: "SYSTEM CONTEXT" },
];

export default function HomePage() {
  return <div>
    <section className="home-hero"><div className="home-hero__copy"><p className="ds-eyebrow">MANUFACTURING OS / TECHNICAL SOURCING</p><h1>Manufacturing decisions, made inspectable.</h1><p className="home-hero__lead">A drawing-led interface for hardware teams moving from CAD to a qualified manufacturing route, quote, and production evidence.</p><div className="home-hero__actions"><Button href="/rfq" size="lg">Upload CAD / Request quote <ArrowRight size={16} /></Button><Link href="/parts/robot-joint-housing" className="text-link">Explore a technical part</Link></div><div className="home-hero__signals"><span><Check size={14} /> Revision-aware intake</span><span><Check size={14} /> Feature-level inspection</span><span><Check size={14} /> China manufacturing coordination</span></div></div><div className="home-hero__diagram"><div className="home-hero__diagram-grid" /><div className="home-hero__diagram-head"><span>FLOW / 001</span><span>CAD → RFQ → QC</span></div><div className="home-hero__diagram-route"><div><span>01</span><strong>CAD</strong><small>released files</small></div><i /><div><span>02</span><strong>ROUTE</strong><small>process + supplier</small></div><i /><div><span>03</span><strong>EVIDENCE</strong><small>inspection record</small></div></div><div className="home-hero__diagram-foot"><span>STATUS</span><StatusTag tone="green">READY TO REVIEW</StatusTag></div></div></section>

    <section className="home-section home-section--signals"><div className="home-kicker"><span>THE SYSTEM VIEW</span><span>BUILT FOR ENGINEERS</span></div><div className="home-statement"><h2>Precision is a sequence of decisions.</h2><p>Manufacturing OS keeps the technical context attached as a part moves through discovery, intake, routing, quoting, inspection, and repeat production.</p></div><div className="home-stat-grid"><div><Activity size={18} /><strong>01</strong><span>Understand the geometry</span></div><div><Ruler size={18} /><strong>02</strong><span>Choose the route</span></div><div><Shield size={18} /><strong>03</strong><span>Prove acceptance</span></div><div><Layers size={18} /><strong>04</strong><span>Carry the revision</span></div></div></section>

    <section className="home-section"><SectionHeading eyebrow="EXPLORE THE SYSTEM" title="Technical pages with a shared operating language" description="Each page type has a different job. The visual grammar stays stable: strong references, compact metadata, clear action, and evidence you can inspect." /><div className="home-system-grid">{systems.map((system) => <Link key={system.code} href={system.href} className="home-system-card"><span>{system.code} / {system.tag}</span><h3>{system.title}</h3><p>{system.body}</p><span className="home-system-card__link">Open view <ArrowRight size={15} /></span></Link>)}</div></section>

    <section className="home-section home-section--dark"><div className="home-dark-grid"><div><p className="ds-eyebrow">RFQ / THE FIRST HANDOFF</p><h2>Start with the files. Keep the questions visible.</h2><p>Upload the current CAD, drawing, BOM, and requirement set. The intake is designed to identify missing information before a route becomes a quote.</p><Button href="/rfq" variant="secondary">Open RFQ intake <ArrowRight size={16} /></Button></div><TechnicalPanel className="home-route-panel" label="ROUTE STATUS"><div className="home-route-row"><span>01</span><strong>Upload files</strong><StatusTag tone="green">READY</StatusTag></div><div className="home-route-row"><span>02</span><strong>Clarify requirements</strong><StatusTag tone="blue">VISIBLE</StatusTag></div><div className="home-route-row"><span>03</span><strong>Route + inspect</strong><StatusTag tone="neutral">TRACEABLE</StatusTag></div><div className="home-route-row"><span>04</span><strong>Quote + repeat</strong><StatusTag tone="neutral">REVISIONED</StatusTag></div></TechnicalPanel></div></section>

    <section className="home-section home-section--last"><div className="home-cta"><div><p className="ds-eyebrow">A BETTER STARTING POINT</p><h2>Bring a difficult part.</h2><p>We will tell you what is known, what needs a decision, and how the route can be proven.</p></div><Button href="/rfq" size="lg">Request a manufacturing review <ArrowRight size={16} /></Button></div></section>
  </div>;
}
