import Link from "next/link";
import { Activity, ArrowRight, Check, Layers, Ruler, Shield } from "@/components/design-system/icons";
import { Button, SectionHeading, StatusTag, TechnicalPanel } from "@/components/design-system/primitives";

const systems = [
  { code: "01", title: "Parts", body: "Drawing-led routes for the interfaces that make hardware work.", href: "/parts/robot-joint-housing", tag: "TECHNICAL OBJECTS" },
  { code: "02", title: "Capabilities", body: "Process guidance grounded in geometry, workholding, and inspection.", href: "/capabilities/5-axis-machining", tag: "PROCESS FIT" },
  { code: "03", title: "Applications", body: "System views that connect part families to the product being built.", href: "/applications/humanoid-robots", tag: "SYSTEM CONTEXT" },
];

const industries = ["Robotics & automation", "Precision motion", "Industrial equipment", "Energy hardware"];

export default function HomePage() {
  return <div className="home-page">
    <section className="home-hero"><div className="home-hero__copy"><p className="ds-eyebrow">MANUFACTURING OS / ENGINEERED SUPPLY</p><h1>Move from intent to inspected hardware.</h1><p className="home-hero__lead">A high-trust manufacturing interface for teams turning CAD, drawings, and requirements into a controlled route, a useful quote, and evidence at delivery.</p><div className="home-hero__actions"><Button href="/rfq" size="lg">Upload CAD / Request quote <ArrowRight size={16} /></Button><Link href="/parts/robot-joint-housing" className="text-link">Explore a technical part <ArrowRight size={15} /></Link></div><div className="home-hero__signals"><span><Check size={14} /> Revision-aware intake</span><span><Check size={14} /> Feature-level inspection</span><span><Check size={14} /> Coordinated China production</span></div></div><div className="home-hero__diagram"><div className="home-hero__diagram-grid" /><div className="home-hero__diagram-head"><span>CONTROL LOOP / 001</span><span>CAD → ROUTE → EVIDENCE</span></div><div className="home-hero__diagram-route"><div><span>01</span><strong>UNDERSTAND</strong><small>released files</small></div><i /><div><span>02</span><strong>COORDINATE</strong><small>process + supplier</small></div><i /><div><span>03</span><strong>PROVE</strong><small>inspection record</small></div></div><div className="home-hero__diagram-foot"><span>STATUS</span><StatusTag tone="green">READY TO REVIEW</StatusTag></div></div></section>

    <section className="home-trust"><div className="home-trust__inner"><p className="ds-eyebrow">WHY TEAMS USE THE SYSTEM</p><div className="home-trust__grid"><div><strong>01</strong><h3>Technical context stays attached</h3><p>Every handoff keeps the revision, interfaces, process assumptions, and acceptance criteria visible.</p></div><div><strong>02</strong><h3>Decisions are made inspectable</h3><p>We surface the unknowns before a supplier route turns them into cost or schedule risk.</p></div><div><strong>03</strong><h3>Production has a clear record</h3><p>Quote, route, inspection, and release evidence belong to one controlled manufacturing story.</p></div></div></div></section>

    <section className="home-section home-section--signals"><div className="home-kicker"><span>THE SYSTEM VIEW</span><span>BUILT FOR ENGINEERS</span></div><div className="home-statement"><h2>Precision is a sequence of decisions.</h2><p>Manufacturing OS gives hardware teams one operating language from the first file review to repeat production. It is a company front door and a working interface for the details that make a part manufacturable.</p></div><div className="home-stat-grid"><div><Activity size={18} /><strong>01</strong><span>Understand the geometry</span></div><div><Ruler size={18} /><strong>02</strong><span>Choose the route</span></div><div><Shield size={18} /><strong>03</strong><span>Prove acceptance</span></div><div><Layers size={18} /><strong>04</strong><span>Carry the revision</span></div></div></section>

    <section className="home-section"><SectionHeading eyebrow="EXPLORE THE SYSTEM" title="A manufacturing layer that reads like the work" description="Different pages answer different questions. The visual grammar stays disciplined so teams can move from a part to a process, an application, or an RFQ without losing the thread." /><div className="home-system-grid">{systems.map((system) => <Link key={system.code} href={system.href} className="home-system-card"><span>{system.code} / {system.tag}</span><h3>{system.title}</h3><p>{system.body}</p><span className="home-system-card__link">Open view <ArrowRight size={15} /></span></Link>)}</div></section>

    <section className="home-network"><div className="home-network__copy"><p className="ds-eyebrow">MANUFACTURING NETWORK</p><h2>Built for difficult hardware, coordinated across the route.</h2><p>We connect engineering intent to capable production partners, then keep the acceptance trail visible as the work moves through machining, finishing, inspection, and delivery.</p><Link href="/network" className="text-link">See how the network works <ArrowRight size={15} /></Link></div><div className="home-network__visual"><div className="network-node network-node--main">MOS<span>CONTROL</span></div><div className="network-node network-node--one">CAD<span>INPUT</span></div><div className="network-node network-node--two">CNC<span>ROUTE</span></div><div className="network-node network-node--three">QC<span>PROOF</span></div><i className="network-line network-line--one" /><i className="network-line network-line--two" /><i className="network-line network-line--three" /></div></section>

    <section className="home-section home-section--industries"><SectionHeading eyebrow="WHERE WE WORK" title="Manufacturing depth for systems that cannot afford ambiguity" /><div className="industry-grid">{industries.map((industry, index) => <div key={industry}><span>0{index + 1}</span><strong>{industry}</strong><p>Geometry-led sourcing, route planning, and evidence that travels with the part.</p></div>)}</div></section>

    <section className="home-section home-section--dark"><div className="home-dark-grid"><div><p className="ds-eyebrow">RFQ / THE FIRST HANDOFF</p><h2>Start with the files. Keep the questions visible.</h2><p>Upload the current CAD, drawing, BOM, and requirement set. The intake identifies missing information before a route becomes a quote.</p><Button href="/rfq" variant="secondary">Open RFQ intake <ArrowRight size={16} /></Button></div><TechnicalPanel className="home-route-panel" label="ROUTE STATUS"><div className="home-route-row"><span>01</span><strong>Upload files</strong><StatusTag tone="green">READY</StatusTag></div><div className="home-route-row"><span>02</span><strong>Clarify requirements</strong><StatusTag tone="blue">VISIBLE</StatusTag></div><div className="home-route-row"><span>03</span><strong>Route + inspect</strong><StatusTag tone="neutral">TRACEABLE</StatusTag></div><div className="home-route-row"><span>04</span><strong>Quote + repeat</strong><StatusTag tone="neutral">REVISIONED</StatusTag></div></TechnicalPanel></div></section>

    <section className="home-section home-section--last"><div className="home-cta"><div><p className="ds-eyebrow">A BETTER STARTING POINT</p><h2>Bring a difficult part.</h2><p>We will tell you what is known, what needs a decision, and how the route can be proven.</p></div><Button href="/rfq" size="lg">Request a manufacturing review <ArrowRight size={16} /></Button></div></section>
  </div>;
}
