// Core object model for Manufacturing OS.
//
// This file is the single source of truth for the shape of every domain
// object in the system. The frontend shell currently reads mock data that
// conforms to these types (see lib/mock/*). When Sanity/Postgres-backed
// data is introduced, only lib/data.ts and lib/mock/* should need to
// change -- these types and every component built on them stay put.
//
// UQ-1 resolution (docs/architecture/entity-publishing-system/migration-plan.md,
// resolved by issue #25): this file's `Part` interface below was the
// PRIVATE, RFQ-specific physical part concept (bound to one CAD package /
// revision / RFQ), which collided in name with the PUBLIC "Part" knowledge
// entity introduced by the entity-publishing architecture (see
// lib/content/types.ts). Per the issue's explicit instruction, the private
// concept here is renamed `PartInstance`; `Part` is reserved for the public
// knowledge entity. `PartInstance` may reference a public `Part` by a
// future `contentPartId` field once the internal ops app is wired to the
// content layer -- not added speculatively in this pass.

/** Provenance rule: never treat an AI guess, a marketing claim, verified
 * documentation, a quote and a proven production outcome as equivalent. */
export type SourceType =
  | "ai_inferred"
  | "supplier_marketing"
  | "documentation_verified"
  | "quote_derived"
  | "production_proven"
  | "manual_entry";

export type ConfidenceLevel = "low" | "medium" | "high" | "verified";

export interface Evidence {
  id: string;
  summary: string;
  sourceType: SourceType;
  url?: string;
  capturedAt: string;
}

/** Shared metadata every important object should carry. */
export interface Traceable {
  id: string;
  status: string;
  source: SourceType;
  confidence: ConfidenceLevel;
  revision?: number;
  createdAt: string;
  updatedAt: string;
  owner: string;
  evidence: Evidence[];
  lastVerified?: string;
}

export type DemandStage =
  | "search"
  | "visitor"
  | "cad_rfq"
  | "quote"
  | "paid"
  | "repeat";

/** Distinguishes an externally observed market signal (search volume we do
 * not control) from a signal generated by our own coverage or transactions
 * (our search console, our site analytics, our RFQ/quote/order system), so
 * the two are never confused when reading a demand funnel. */
export type DemandSignalSource =
  | "external_market_estimate"
  | "search_console"
  | "site_analytics"
  | "outbound_research"
  | "rfq_intake"
  | "quote_system"
  | "paid_transaction";

export interface DemandSignal {
  stage: DemandStage;
  value: number;
  unit: string;
  period: string;
  signalSource: DemandSignalSource;
}

// ---------------------------------------------------------------------------
// Market / knowledge objects
// ---------------------------------------------------------------------------

export interface Market extends Traceable {
  name: string;
  description: string;
  sizeUsd: number;
  growthRatePct: number;
  industryIds: string[];
  geographyIds: string[];
}

export interface Industry extends Traceable {
  name: string;
  description: string;
  marketIds: string[];
}

export interface Application extends Traceable {
  name: string;
  description: string;
  industryId: string;
  componentIds: string[];
  engineeringProblemIds: string[];
}

export interface Component extends Traceable {
  name: string;
  category: string;
  description: string;
  applicationIds: string[];
  materialIds: string[];
  processIds: string[];
  engineeringProblemIds: string[];
  opportunityIds: string[];
  supplierIds: string[];
  cadPackageIds: string[];
  searchSurfaceIds: string[];
  demandSignals: DemandSignal[];
}

export interface Material extends Traceable {
  name: string;
  category: string;
  properties: Record<string, string>;
  componentIds: string[];
  processIds: string[];
}

export interface ManufacturingProcess extends Traceable {
  name: string;
  category: string;
  description: string;
  componentIds: string[];
  materialIds: string[];
  supplierCapabilityIds: string[];
}

export interface EngineeringProblem extends Traceable {
  name: string;
  description: string;
  componentIds: string[];
  applicationIds: string[];
}

export interface Geography extends Traceable {
  name: string;
  region: string;
  country: string;
  marketIds: string[];
  supplierIds: string[];
}

export interface SearchQuery extends Traceable {
  query: string;
  volumeMonthly: number;
  intent: "informational" | "commercial" | "transactional";
  componentIds: string[];
  searchSurfaceId: string;
}

export type SearchSurfaceIndexState = "indexed" | "noindex" | "draft";

export interface SearchSurface extends Traceable {
  name: string;
  slug: string;
  geographyId: string;
  locale: string;
  canonical: boolean;
  indexState: SearchSurfaceIndexState;
  componentIds: string[];
  searchQueryIds: string[];
  monthlyVisitors: number;
  qualifiedVisitors: number;
}

export type OpportunityStage =
  | "identified"
  | "qualifying"
  | "cad_received"
  | "rfq_active"
  | "quoted"
  | "won"
  | "lost";

export type RiskLevel = "low" | "medium" | "high";

/**
 * Market-level opportunity: Demand x Capability x Competition x Margin x
 * Risk for a market/component combination, independent of any one
 * customer. This is the Discovery-layer "opportunity" the system map
 * describes. It is distinct from a CommercialOpportunity (below), which is
 * a specific customer's deal moving through a sales pipeline. A commercial
 * opportunity may reference the market opportunity that qualified it via
 * `marketOpportunityId`, but the two are never conflated into one object.
 */
export interface MarketOpportunity extends Traceable {
  name: string;
  description: string;
  marketId: string;
  componentIds: string[];
  demandScore: number;
  capabilityScore: number;
  competitionScore: number;
  marginPotentialPct: number;
  riskLevel: RiskLevel;
}

/**
 * Commercial opportunity: a specific customer's deal, tracked through a
 * sales-style pipeline stage. Renamed conceptually from a generic
 * "Opportunity" to make explicit that this is pipeline/deal semantics, not
 * market-level opportunity scoring (see MarketOpportunity above).
 */
export interface Opportunity extends Traceable {
  name: string;
  description: string;
  opportunityType: "commercial";
  marketOpportunityId?: string;
  stage: OpportunityStage;
  marketId: string;
  geographyId: string;
  componentIds: string[];
  estValueUsd: number;
  demandSignals: DemandSignal[];
}

export interface Competitor extends Traceable {
  name: string;
  description: string;
  website?: string;
  marketIds: string[];
  geographyIds: string[];
  strengths: string[];
  weaknesses: string[];
}

// ---------------------------------------------------------------------------
// Supply objects
// ---------------------------------------------------------------------------

export type CapabilityLayer = "declared" | "observed";

export interface SizeEnvelopeMm {
  lengthMax: number;
  widthMax: number;
  heightMax: number;
}

export interface QuantityRange {
  min: number;
  max: number;
}

export interface SupplierCapability extends Traceable {
  supplierId: string;
  processId: string;
  materialIds: string[];
  layer: CapabilityLayer;
  toleranceMm?: number;
  sizeEnvelopeMm: SizeEnvelopeMm;
  quantityRange: QuantityRange;
  finishCapabilities: string[];
  qcCapabilities: string[];
  constraints: string;
  notes: string;
}

export interface SupplierMachineEvidence extends Traceable {
  supplierId: string;
  machineType: string;
  description: string;
  processId: string;
}

export interface SupplierPerformance extends Traceable {
  supplierId: string;
  onTimeRatePct: number;
  qualityScorePct: number;
  avgLeadTimeDays: number;
  totalOrders: number;
  repeatOrderRatePct: number;
}

export interface Supplier extends Traceable {
  name: string;
  website?: string;
  geographyId: string;
  description: string;
  declaredCapabilityIds: string[];
  observedCapabilityIds: string[];
  machineEvidenceIds: string[];
  performanceId?: string;
  componentIds: string[];
}

// ---------------------------------------------------------------------------
// Customer / execution objects
// ---------------------------------------------------------------------------

export interface Contact extends Traceable {
  name: string;
  companyId: string;
  email: string;
  role: string;
}

export interface Company extends Traceable {
  name: string;
  industryId: string;
  geographyId: string;
  contactIds: string[];
}

export interface Revision extends Traceable {
  partId: string;
  revisionCode: string;
  changeSummary: string;
  released: boolean;
  internalFileRef: string;
}

/** The private, RFQ-specific physical part instance -- bound to one CAD
 * package, one component, and a chain of revisions. Not the public "Part"
 * knowledge entity (see lib/content/types.ts); see the UQ-1 note above. */
export interface PartInstance extends Traceable {
  name: string;
  cadPackageId: string;
  componentId: string;
  materialId: string;
  processId: string;
  revisionIds: string[];
  currentRevisionId: string;
}

export interface CadPackage extends Traceable {
  name: string;
  companyId: string;
  opportunityId: string;
  componentId: string;
  partIds: string[];
  internalFileRef: string;
  rfqId?: string;
}

export type RfqStage =
  | "intake"
  | "normalized"
  | "supplier_matching"
  | "quoting"
  | "quoted"
  | "closed_won"
  | "closed_lost";

/** Whether the RFQ has everything needed to be released to suppliers. */
export type RfqReadinessState = "ready" | "missing_information" | "conflicts_open";

export interface Rfq extends Traceable {
  name: string;
  companyId: string;
  cadPackageId: string;
  componentId: string;
  /** Immutable binding to the exact part/revision this RFQ was normalized
   * against -- does not follow Part.currentRevisionId if it later advances. */
  partId: string;
  revisionId: string;
  materialId: string;
  processId: string;
  finish: string;
  criticalRequirements: string[];
  inspectionRequirement: string;
  deliveryRequirement: string;
  missingInformation: string[];
  conflicts: string[];
  assumptions: string[];
  readinessState: RfqReadinessState;
  stage: RfqStage;
  quantity: number;
  targetUnitPriceUsd?: number;
  dueDate: string;
  supplierQuoteIds: string[];
  customerQuoteId?: string;
}

export interface SupplierQuote extends Traceable {
  rfqId: string;
  supplierId: string;
  /** Immutable binding to the exact revision this quote was priced against,
   * carried forward from the RFQ regardless of later revision changes. */
  revisionId: string;
  unitPriceUsd: number;
  toolingNreUsd: number;
  leadTimeDays: number;
  quantity: number;
  moq: number;
  materialId: string;
  finish: string;
  inspectionScope: string;
  shippingFreightUsd: number;
  incoterm: string;
  paymentTerms: string;
  currency: string;
  quoteValidUntil: string;
  notes: string;
  selected: boolean;
}

export type CustomerQuoteStatus = "draft" | "sent" | "accepted" | "declined";

export interface CustomerQuote extends Traceable {
  rfqId: string;
  companyId: string;
  supplierQuoteId: string;
  /** Immutable binding to the exact revision this commercial quote was
   * issued against. */
  revisionId: string;
  sellUnitPriceUsd: number;
  marginPct: number;
  status: CustomerQuoteStatus;
  orderId?: string;
}

export type OrderStatus =
  | "pending"
  | "in_production"
  | "qc"
  | "shipped"
  | "delivered"
  | "cancelled";

export interface Order extends Traceable {
  customerQuoteId: string;
  companyId: string;
  supplierId: string;
  componentId: string;
  /** Immutable binding to the exact revision released for production. */
  revisionId: string;
  orderValueUsd: number;
  status: OrderStatus;
  productionJobId?: string;
}

export type ProductionStage =
  | "queued"
  | "in_progress"
  | "qc"
  | "rework"
  | "complete";

export interface ProductionJob extends Traceable {
  orderId: string;
  supplierId: string;
  partId: string;
  revisionId: string;
  stage: ProductionStage;
  startDate: string;
  dueDate: string;
  qcResultId?: string;
}

export type QcOutcome = "pass" | "fail" | "rework";

export interface QcResult extends Traceable {
  productionJobId: string;
  partId: string;
  revisionId: string;
  result: QcOutcome;
  inspector: string;
  notes: string;
  measurements: { dimension: string; nominal: string; actual: string; withinTolerance: boolean }[];
}

export interface Outcome extends Traceable {
  orderId: string;
  onTime: boolean;
  qualityPass: boolean;
  actualLeadTimeDays: number;
  actualCostUsd: number;
  marginRealizedPct: number;
  repeatPurchase: boolean;
  feedback: string;
}

// ---------------------------------------------------------------------------
// Intelligence objects
// ---------------------------------------------------------------------------

export interface SearchPerformanceRecord extends Traceable {
  searchSurfaceId: string;
  period: string;
  impressions: number;
  clicks: number;
  qualifiedVisitors: number;
  cadUploads: number;
}

export interface DemandLearningRecord extends Traceable {
  componentId: string;
  period: string;
  insight: string;
  demandDeltaPct: number;
}

export interface SupplierLearningRecord extends Traceable {
  supplierId: string;
  period: string;
  insight: string;
  performanceDeltaPct: number;
}

export interface EconomicsRecord extends Traceable {
  period: string;
  revenueUsd: number;
  grossMarginPct: number;
  avgOrderValueUsd: number;
  ordersCount: number;
}
